////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

include::_common/attributes.adoc[]

:context: router

= {RouterBook}

// Overview
include::assemblies/overview.adoc[leveloffset=+1]

// Getting started
include::assemblies/getting-started.adoc[leveloffset=+1]

// Configuring a router network topology
include::assemblies/creating-router-network-topology.adoc[leveloffset=+1]

// Configuring a router
include::assemblies/configuring-router.adoc[leveloffset=+1]

// Routing messages through the router network
include::routing.adoc[leveloffset=+1]

[id="monitoring-managing-router-network"]
== Monitoring and managing the router network
include::modules/starting-routers.adoc[leveloffset=+2]
include::logging.adoc[leveloffset=+2]
include::using-console.adoc[leveloffset=+2]
include::monitoring-using-qdstat.adoc[leveloffset=+2]
include::managing-using-qdmanage.adoc[leveloffset=+2]

// Technical Details and Specifications
include::technical-details-specifications.adoc[leveloffset=+1]

// Revision information
include::revision-info.adoc[]
