////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

[id='router-network-connections']
= Network Connections

Connections define how the router communicates with clients, other routers, and brokers. You can configure _incoming connections_ to define how the router listens for data from clients and other routers, and you can configure _outgoing connections_ to define how the router sends data to other routers and brokers.

[id='adding-incoming-connections']
== Listening for Incoming Connections

{RouterName} provides _listeners_ that accept client connections.
A client connecting to a router listener uses the
same methods that it would use to connect to a broker. From the
client's perspective, the router connection and link establishment are
identical to broker connection and link establishment.

Several types of listeners are defined by their role.

[options="header",cols="20,80"]
|===
| Role | Description
| normal | The connection is used for AMQP clients using normal message delivery.
| inter-router | The connection is assumed to be to another interior router in the network.  Inter-router discovery and routing protocols can only be used over inter-router connections.
| route-container | The connection is a broker or other resource that holds known addresses. The router will use this connection to create links as necessary. The addresses are available for routing only after the remote resource has created a connection.
| edge | The connection is between an edge router and an interior router.
|===

.Procedure

. In the router's configuration file, add a `listener`:
+
--
[options="nowrap",subs="+quotes"]
----
listener {
    host: _HOST_NAME/ADDRESS_
    port: _PORT_NUMBER/NAME_
    ...
}
----

`host`:: Either an IP address (IPv4 or IPv6) or hostname on which the router should listen for incoming connections.
`port`:: The port number or symbolic service name on which the router should listen for incoming connections.

For information about additional attributes, see link:{qdrouterdConfManPageUrl}#_listener[listener] in the `qdrouterd.conf` man page.
--

. If necessary, xref:securing-incoming-connections[secure the connection].
+
If you have set up SSL/TLS or SASL in your environment, you can configure the router to only accept encrypted or authenticated communication on this connection.

. If you want the router to listen for incoming connections on additional hosts or ports, configure an additional `listener` entity for each host and port.

[id='adding-outgoing-connections']
== Adding Outgoing Connections

You can configure {RouterName} to create outbound connections to
messaging brokers or other AMQP entities using _connectors_. A
connector is defined with the network address of the broker and the
name or names of the resources that are available in that broker. When
a router connects to a broker through a connector, it uses the same
methods a normal messaging client would use when connecting to the
broker.

Several types of connectors are defined by their role.

[options="header",cols="20,80"]
|===
| Role | Description
| normal | The connection is used for AMQP clients using normal message delivery. On this connector the router will initiate the connection but it will never create any links. Links are to be created by the peer that accepts the connection.
| inter-router | The connection is assumed to be to another interior router in the network.  Inter-router discovery and routing protocols can only be used over inter-router connections.
| route-container | The connection is to a broker or other resource that holds known addresses. The router will use this connection to create links as necessary. The addresses are available for routing only after the router has created a connection to the remote resource.
| edge | The connection is between an edge router and an interior router.
|===

// Adding this here for now; in the future it might be better to have separate procedures for creating inter-router and route-container connections.
When a router connects to a broker, the broker might provide backup connection data that the router can use if the primary connection fails. If the primary connection fails, the router attempts to reconnect by using a combination of the primary and -- if provided -- backup connections in round-robin fashion until the connection is successful. For more information about viewing the backup connection data provided by the broker, see xref:managing-connectors[].

.Procedure

. In the router's configuration file, add a `connector`:
+
--
[options="nowrap",subs="+quotes"]
----
connector {
    name: _NAME_
    host: _HOST_NAME/ADDRESS_
    port: _PORT_NUMBER/NAME_
    ...
}
----

`name`:: The name of the `connector`. You should specify a name that describes the entity to which the connector connects. This name is used by configured addresses (for example, a `linkRoute` entity) in order to specify which connection should be used for them.
`host`:: Either an IP address (IPv4 or IPv6) or hostname on which the router should connect.
`port`:: The port number or symbolic service name on which the router should connect.

For information about additional attributes, see link:{qdrouterdConfManPageUrl}#_connector[connector] in the `qdrouterd.conf` man page.
--

. If necessary, xref:securing-outgoing-connections[secure the connection].
+
If you have set up SSL/TLS or SASL in your environment, you can configure the router to only send encrypted or authenticated communication on this connection.

. For each remaining router or broker to which this router should connect, configure an additional `connector` entity.


include::modules/connection-failover.adoc[leveloffset=+1]
