////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

= Management

You can manage {RouterName} using both graphical and command-line tools.

{ConsoleName}:: A graphical tool for monitoring and managing {RouterName} routers.
`qdstat`:: A command-line tool for monitoring the status of {RouterName} routers.
`qdmanage`:: A command-line tool for viewing and updating the configuration of {RouterName} routers.

// Using the Console
include::using-console.adoc[leveloffset=+1]

// Monitoring Using qdstat
include::monitoring-using-qdstat.adoc[leveloffset=+1]

// Managing Using qdmanage
include::managing-using-qdmanage.adoc[leveloffset=+1]

// Management Entities
include::management-entities.adoc[leveloffset=+1]
