PYTHONPATH="/home/chug/git/qpid-dispatch/python:/home/chug/git/qpid-dispatch/build/python:/home/chug/git/qpid-dispatch/tests:/opt/local/lib/python3.7/site-packages:/opt/local/lib64/proton/bindings/python:"
PATH="/home/chug/git/qpid-dispatch/build:/home/chug/git/qpid-dispatch/build/tests:/home/chug/git/qpid-dispatch/build/router:/home/chug/git/qpid-dispatch/tools:/home/chug/git/qpid-dispatch/build/tools:/home/chug/git/qpid-dispatch/bin:/opt/local/sbin:/opt/local/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/chug/.dotnet/tools:/home/chug/bin"
MANPATH="/home/chug/git/qpid-dispatch/build/doc/man::"
SOURCE_DIR="/home/chug/git/qpid-dispatch"
BUILD_DIR="/home/chug/git/qpid-dispatch/build"
QPID_DISPATCH_HOME="/home/chug/git/qpid-dispatch"
QPID_DISPATCH_LIB="/home/chug/git/qpid-dispatch/build/src/"
QPID_DISPATCH_RUNNER=""
MALLOC_CHECK_="3"
MALLOC_PERTURB_="153"
TSAN_OPTIONS=""
ASAN_OPTIONS=""
LSAN_OPTIONS=""
export PYTHONPATH PATH MANPATH SOURCE_DIR BUILD_DIR QPID_DISPATCH_HOME QPID_DISPATCH_LIB QPID_DISPATCH_RUNNER MALLOC_CHECK_ MALLOC_PERTURB_ TSAN_OPTIONS ASAN_OPTIONS LSAN_OPTIONS
