////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// creating-router-network-topology.adoc

[id='adding-routers-router-network-{context}']
= Adding routers to the router network

After planning the router network topology, you implement it by adding each router to the router network. You add routers one at a time.

This procedure describes the workflow required to add a router to the router network.

.Prerequisites

* {RouterName} is installed on the host.

.Procedure

. xref:configuring-router-properties-router[Configure essential router properties].
+
To participate in a router network, a router must be configured with a unique ID and an operating mode.

. xref:configuring-network-connections-router[Configure network connections].

.. Connect the router to any other routers in the router network.
+
Repeat this step for each additional router to which you want to connect this router.

.. If the router should connect with an AMQP client, configure a client connection.

.. If the router should connect to an external AMQP container (such as a message broker), configure the connection.

. xref:securing-network-connections-router[Secure each of the connections that you configured in the previous step].

. (Optional) Configure any additional properties.
+
These properties should be configured the same way on each router. Therefore, you should only configure each one once, and then copy the configuration to each additional router in the router network.

** xref:authorizing-access-to-messaging-resources[Authorization]
+
If necessary, configure policies to control which messaging resources clients are able to access on the router network.

** xref:routing[Routing]
+
{RouterName} automatically routes messages without any configuration: clients can send messages to the router network, and the router automatically routes them to their destinations. However, you can configure the routing to meet your exact requirements. You can configure the routing patterns to be used for certain addresses, create waypoints and autolinks to route messages through broker queues, and create link routes to connect clients to brokers.

** xref:logging[Logging]
+
You can set the default logging configuration to ensure that events are logged at the correct level for your environment.

. Start the router.
