////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// configuring-network-connections.adoc

[id='connecting-routers-external-amqp-containers-{context}']
= Connecting routers and external AMQP containers

You can connect a router to an external AMQP container (such as a message broker). You can configure the router to either listen for connections from the AMQP container, or to initiate connections to it.

.Procedure

include::{FragmentDir}/fragment-router-open-config-file-step.adoc[]

. Do one of the following:

** If the router should listen for connections from the AMQP container, add a `listener`.
+
--
This example creates a `listener` that accepts connections from a broker. The addresses on the broker will be available for routing only after the broker has created the connection.

[options="nowrap",subs="+quotes"]
----
listener {
    name: my-broker
    host: 0.0.0.0
    port: 5672
    role: route-container
    ...
}
----

`name`:: The name of the `listener`. Specify a name that describes the entity to which the router will connect.
`host`:: Either an IP address (IPv4 or IPv6) or hostname on which the router should listen.
`port`:: The port number or symbolic service name on which the router should listen.
`role`:: The role of the connection. Specify `route-container` to indicate that this connection is for an AMQP container that holds known addresses.
--

** If the router should initiate a connection to the broker, add a `connector`.
+
--
This example creates a `connector` that initiates connections to a broker. The addresses on the broker will be available for routing once the router creates the connection and it is accepted by the broker.

[options="nowrap",subs="+quotes"]
----
connector {
    name: my-broker
    host: 192.0.2.10
    port: 5672
    role: route-container
    ...
}
----
`name`:: The name of the `connector`. Specify a name that describes the entity to which the router will connect.
`host`:: Either an IP address (IPv4 or IPv6) or hostname to which the router should connect.
`port`:: The port number or symbolic service name to which the router should connect.
`role`:: The role of the connection. Specify `route-container` to indicate that this connection is for an AMQP container that holds known addresses.
--
