////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// configuring-network-connections.adoc

[id='connecting-routers-clients-{context}']
= Connecting routers and clients

You can enable connections between a router and a client. You can configure the router to either listen for connections from a client, or to initiate connections to a client.

Once the connection is enabled on the router, clients can connect to it using the same methods they use to connect to a broker. From the client's perspective, the router connection and link establishment are identical to a broker connection and link establishment.

.Procedure

include::{FragmentDir}/fragment-router-open-config-file-step.adoc[]

. Do one of the following:

** If the router should listen for connections from the client, add a `listener`.
+
--
[options="nowrap",subs="+quotes"]
----
listener {
    host: primary.example.com
    port: 5672
    role: normal
    failoverUrls: secondary.example.com:20000, tertiary.example.com
    ...
}
----

`host`:: Either an IP address (IPv4 or IPv6) or hostname on which the router should listen.
`port`:: The port number or symbolic service name on which the router should listen.
`role`:: The role of the connection. Specify `normal` to indicate that this connection should be used for message delivery for AMQP clients.
`failoverUrls` (optional):: A comma-separated list of backup URLs the client can use to reconnect if the established connection is lost. Each URL should use the following form:
+
`[(amqp|amqps|ws|wss)://](__HOST__|__IP ADDRESS__)[:port]`
+
For more information, see xref:connection-failover-router[].
--

** If the router should initiate a connection to the client, add a `connector`.
+
--
The router will use this `connector` to initiate the connection, but will not create any links. Links are only created by the client that accepts the connection.

[options="nowrap",subs="+quotes"]
----
connector {
    host: 192.0.2.10
    port: 6000
    role: normal
    ...
}
----

`host`:: Either an IP address (IPv4 or IPv6) or hostname to which the router should connect.
`port`:: The port number or symbolic service name to which the router should connect.
`role`:: The role of the connection. Specify `normal` to indicate that this connection should be used for message delivery for AMQP clients.
--
