////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module included in the following assemblies:
//
// important-terms-concepts.adoc

[id='overview-of-amqp-{context}']
= Overview of AMQP

{RouterName} implements version 1.0 of the Advanced Message Queueing Protocol (AMQP) specification. Therefore, you should understand several key AMQP terms and concepts before deploying or configuring {RouterName}.

AMQP is a wire-level messaging protocol for transferring messages between applications called _containers_. Containers contain addressable entities (such as queues) called _nodes_. Messages are transferred between connected containers over _links_. A link is a unidirectional route between nodes. Essentially, a link is a channel for sending or receiving messages. Links are established over _sessions_, which are contexts for sending and receiving messages. Sessions are established within a _connection_, which is a channel for communication between containers.

.Additional resources

* link:http://www.amqp.org/resources/download[OASIS AMQP 1.0 Specification]
* link:https://dzone.com/refcardz/amqp-essentials?chapter=1[AMQP Essentials Refcard]
* link:https://channel9.msdn.com/Blogs/Subscribe[Video series introducing AMQP 1.0]
