////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module included in the following assemblies:
//
// important-terms-concepts.adoc

[id='router-addresses-{context}']
= Addresses

An _address_ is the name of a message source or destination endpoint in the messaging network. AMQP addresses control the flow of messages across the router network. 

Addresses can designate various types of entities in a messaging network, such as:

* Endpoint processes that consume data or offer a service
* Topics that match multiple consumers to multiple producers
* Entities within a message broker:
** Queues
** Durable Topics
** Exchanges

{RouterName} treats addresses as opaque strings. Therefore, when creating addresses, you can use whatever syntax makes the most sense for your environment.

[discrete]
== Mobile addresses
Mobile addresses are rendezvous points between senders and receivers. The router aggregates and serializes messages from senders and distributes messages to receivers.

Routers consider addresses to be mobile such that any users of an address may be directly connected to any router in a network and may move around the topology. In cases where messages are broadcast to or balanced across multiple consumers, the users of the address may be connected to multiple routers in the network.

Mobile addresses may be discovered during normal router operation or manually configured.

[discrete]
== Link route addresses
A link route address is a type of configured address that designates a queue, topic, or service on an external container such as a message broker. For link route addresses, {RouterName} propagates a separate link attachment to the broker resource for each incoming client link. The router does not automatically create any links to the broker resource.

In addition, with link route addresses, the router network does not participate in aggregated message distribution. The router simply passes message delivery and settlement between the two end points.
