
= Qpid Dispatch Router Documentation

This directory contains the documentation for Qpid Dispatch Router. The documentation consists of a user guide, man pages, and a configuration reference.

[source,bash,options="nowrap",subs="+quotes"]
----
/doc
  ├── book  # Files for the Dispatch Router user guide
  ├── common  # Common content shared between books
  ├── internal-resources  # Guidelines for writing documentation
  ├── man  # Man page source files and scripts
----

== Contributing to the Documentation

Apache Qpid welcomes contributions from the community. To contribute to the documentation, see the link:internal-resources/contrib-guide.adoc[Contributor's Guide].

To file a documentation bug or tell us about any other issue with the documentation, visit the link:https://issues.apache.org/jira/projects/DISPATCH[Apache Dispatch JIRA project]. When creating the issue, be sure to select the `Documentation` component, and be as specific as possible about the changes you would like to see.

[id='building-documentation']
== Building the Documentation

Before you can build the documentation, you must have the link:https://github.com/asciidoctor/asciidoctor[`asciidoctor`] package installed.

Clone the qpid-dispatch repository:

[source,bash,options="nowrap",subs="+quotes"]
----
$ git clone https://github.com/apache/qpid-dispatch.git
$ cd qpid-dispatch
----

Build the documentation:

[source,bash,options="nowrap",subs="+quotes"]
----
$ make doc
----
