////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

include::attributes.adoc[]

= {RouterBook}

// Introduction
include::introduction.adoc[leveloffset=+1]

// Theory of Operation
include::theory_of_operation.adoc[leveloffset=+1]

// Getting Started
include::getting-started.adoc[leveloffset=+1]

// Configuration
include::understand-router-configuration.adoc[leveloffset=+1]

// Network Connections
include::configuration-connections.adoc[leveloffset=+1]

// Security
include::configuration-security.adoc[leveloffset=+1]

// Routing
include::routing.adoc[leveloffset=+1]

// Logging
include::logging.adoc[leveloffset=+1]

// Policies
include::policy.adoc[leveloffset=+1]

// Management
include::management.adoc[leveloffset=+1]

// Reliability
include::reliability.adoc[leveloffset=+1]

// Technical Details and Specifications
include::technical-details-specifications.adoc[leveloffset=+1]

[appendix]
include::cyrus-sasl.adoc[leveloffset=+1]

[appendix]
include::configuration-reference.adoc[leveloffset=+1]

// Revision information
include::revision-info.adoc[]
