////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

[[security_config]]
= Security

You can configure {RouterName} to communicate with clients, routers, and brokers in a secure way by authenticating and encrypting the router's connections. {RouterName} supports the following security protocols:

* _SSL/TLS_ for certificate-based encryption and mutual authentication
* _SASL_ for authentication and payload encryption

[[setting_up_ssl_for_encryption_and_authentication]]
== Setting Up SSL/TLS for Encryption and Authentication

Before you can secure incoming and outgoing connections using SSL/TLS encryption and authentication, you must first set up the SSL/TLS profile in the router's configuration file.

// This section assumes that you only need to set up a single SSL profile. Are there scenarios in which customers might need multiple SSL profiles? Would you typically use a single SSL profile for all incoming and outgoing connections, or would you use separate profiles?

.Prerequisites

You must have the following files in PEM format:

* An X.509 CA certificate (used for signing the router certificate for the SSL/TLS server authentication feature).
* A private key (with or without password protection) for the router.
* An X.509 router certificate signed by the X.509 CA certificate.

.Procedure

* In the router's configuration file, add an `sslProfile` section:
+
--
[options="nowrap",subs="+quotes"]
----
sslProfile {
    name: _NAME_
    certDb: _PATH_.pem
    certFile: _PATH_.pem
    keyFile: _PATH_.pem
    password: _PASSWORD/PATH_TO_PASSWORD_FILE_
    ...
}
----

`name`:: A name for the SSL/TLS profile. You can use this name to refer to the profile from the incoming and outgoing connections.
+
For example:
+
[options="nowrap"]
----
name: router-ssl-profile
----

`certDb`:: The absolute path to the database that contains the public certificates of trusted certificate authorities (CA).
+
For example:
+
[options="nowrap"]
----
certDb: /qdrouterd/ssl_certs/ca-cert.pem
----

`certFile`:: The absolute path to the file containing the PEM-formatted public certificate to be used on the local end of any connections using this profile.
+
For example:
+
[options="nowrap"]
----
certFile: /qdrouterd/ssl_certs/router-cert-pwd.pem
----

`keyFile`:: The absolute path to the file containing the PEM-formatted private key for the above certificate.
+
For example:
+
[options="nowrap"]
----
keyFile: /qdrouterd/ssl_certs/router-key-pwd.pem
----

`passwordFile` or `password`:: If the private key is password-protected, you must provide the password by either specifying the absolute path to a file containing the password that unlocks the certificate key, or entering the password directly in the configuration file.
+
For example:
+
[options="nowrap"]
----
password: routerKeyPassword
----

For information about additional `sslProfile` attributes, see xref:router_configuration_file_sslprofile[_sslProfile_] in the _Configuration Reference_.
--

[[setting_up_sasl_for_authentication_and_payload_encryption]]
== Setting Up SASL for Authentication and Payload Encryption

If you plan to use SASL to authenticate connections, you must first add the SASL attributes to the `router` entity in the router's configuration file. These attributes define a set of SASL parameters that can be used by the router's incoming and outgoing connections.

// Do we need to say something here about only supporting Cyrus SASL?

.Prerequisites

Before you can set up SASL, you must have the following:

* xref:generating_sasl_database[The SASL database is generated.]
* xref:configuring_sasl_database[The SASL configuration file is configured.]

.Procedure

* In the router's configuration file, add the following attributes to the `router` section:
+
--
[options="nowrap",subs="+quotes"]
----
router {
    ...
    saslConfigPath: _PATH_
    saslConfigName: _FILE_NAME_
}
----

`saslConfigPath`:: The absolute path to the SASL configuration file.
+
For example:
+
[options="nowrap"]
----
saslConfigPath: /qdrouterd/security
----

`saslConfigName`:: The name of the SASL configuration file. This name should _not_ include the `.conf` file extension.
+
For example:
+
[options="nowrap"]
----
saslConfigName: qdrouterd_sasl
----
--

[[securing_incoming_connections]]
== Securing Incoming Connections

You can secure incoming connections by configuring each connection's `listener` entity for encryption, authentication, or both.

.Prerequisites

Before securing incoming connections, the security protocols you plan to use should be set up.

.Choices

* xref:adding_ssl_encryption_to_incoming_connection[Add SSL/TLS encryption]
* xref:adding_sasl_authentication_to_incoming_connection[Add SASL authentication]
* xref:adding_ssl_client_authentication_to_incoming_connection[Add SSL/TLS client authentication]
* xref:adding_sasl_payload_encryption_to_incoming_connection[Add SASL payload encryption]

[[adding_ssl_encryption_to_incoming_connection]]
=== Adding SSL/TLS Encryption to an Incoming Connection

You can configure an incoming connection to accept encrypted connections only. By adding SSL/TLS encryption, to connect to this router, a remote peer must first start an SSL/TLS handshake with the router and be able to validate the server certificate received by the router during the handshake.

.Procedure

* In the router's configuration file, add the following attributes to the connection's `listener` entity:
+
--
[options="nowrap",subs="+quotes"]
----
listener {
    ...
    sslProfile: _SSL_PROFILE_NAME_
    requireSsl: yes
}
----

`sslProfile`:: The name of the SSL/TLS profile you set up.

`requireSsl`:: Enter `yes` to require all clients connecting to the router on this connection to use encryption.
--

[[adding_sasl_authentication_to_incoming_connection]]
=== Adding SASL Authentication to an Incoming Connection

You can configure an incoming connection to authenticate the client using SASL. You can use SASL authentication with or without SSL/TLS encryption.

.Procedure

* In the router's configuration file, add the following attributes to the connection's `listener` section:
+
--
[options="nowrap",subs="+quotes"]
----
listener {
    ...
    authenticatePeer: yes
    saslMechanisms: _MECHANISMS_
}
----

`authenticatePeer`:: Set this attribute to `yes` to require the router to authenticate the identity of a remote peer before it can use this incoming connection.

`saslMechanisms`:: The SASL authentication mechanism (or mechanisms) to use for peer authentication. You can choose any of the Cyrus SASL authentication mechanisms _except_ for `ANONYMOUS`. To specify multiple authentication mechanisms, separate each mechanism with a space.
+
For a full list of supported Cyrus SASL authentication mechanisms, see link:https://www.cyrusimap.org/sasl/sasl/authentication_mechanisms.html[Authentication Mechanisms^].
--

[[adding_ssl_client_authentication_to_incoming_connection]]
=== Adding SSL/TLS Client Authentication to an Incoming Connection

You can configure an incoming connection to authenticate the client using SSL/TLS.

The base SSL/TLS configuration provides content encryption and server authentication, which means that remote peers can verify the router's identity, but the router cannot verify a peer's identity.

However, you can require an incoming connection to use SSL/TLS client authentication, which means that remote peers must provide an additional certificate to the router during the SSL/TLS handshake. By using this certificate, the router can verify the client's identity without using a username and password.

You can use SSL/TLS client authentication with or without SASL authentication.

.Procedure

* In the router's configuration, file, add the following attribute to the connection's `listener` entity:
+
--
[options="nowrap"]
----
listener {
    ...
    authenticatePeer: yes
}
----

`authenticatePeer`:: Set this attribute to `yes` to require the router to authenticate the identity of a remote peer before it can use this incoming connection.
--

[[adding_sasl_payload_encryption_to_incoming_connection]]
=== Adding SASL Payload Encryption to an Incoming Connection

If you do not use SSL/TLS, you can still encrypt the incoming connection by using SASL payload encryption.

.Procedure

* In the router's configuration file, add the following attributes to the connection's `listener` section:
+
--
[options="nowrap",subs="+quotes"]
----
listener {
    ...
    requireEncryption: yes
    saslMechanisms: _MECHANISMS_
}
----

`requireEncryption`:: Set this attribute to `yes` to require the router to use SASL payload encryption for the connection.

`saslMechanisms`:: The SASL mechanism to use. You can choose any of the Cyrus SASL authentication mechanisms. To specify multiple authentication mechanisms, separate each mechanism with a space.
+
For a full list of supported Cyrus SASL authentication mechanisms, see link:https://www.cyrusimap.org/sasl/sasl/authentication_mechanisms.html[Authentication Mechanisms^].
--

[[securing_outgoing_connections]]
== Securing Outgoing Connections

You can secure outgoing connections by configuring each connection's `connector` entity for encryption, authentication, or both.

.Prerequisites

Before securing outgoing connections, the security protocols you plan to use should be set up.

.Choices

* xref:adding_ssl_authentication_to_outgoing_connection[Add SSL/TLS authentication]
* xref:adding_sasl_authentication_to_outgoing_connection[Add SASL authentication]

[[adding_ssl_authentication_to_outgoing_connection]]
=== Adding SSL/TLS Client Authentication to an Outgoing Connection

If an outgoing connection connects to an external client configured with mutual authentication, you should ensure that the outgoing connection is configured to provide the external client with a valid security certificate during the SSL/TLS handshake.

You can use SSL/TLS client authentication with or without SASL authentication.

.Procedure

* In the router's configuration file, add the `sslProfile` attribute to the connection's `connector` entity:
+
--
[options="nowrap",subs="+quotes"]
----
connector {
    ...
    sslProfile: _SSL_PROFILE_NAME_
}
----

`sslProfile`:: The name of the SSL/TLS profile you set up.
--

[[adding_sasl_authentication_to_outgoing_connection]]
=== Adding SASL Authentication to an Outgoing Connection

You can configure an outgoing connection to provide authentication credentials to the external container. You can use SASL authentication with or without SSL/TLS encryption.

.Procedure

* In the router's configuration file, add the `saslMechanisms` attribute to the connection's `connector` entity:
+
--
[options="nowrap",subs="+quotes"]
----
connector {
    ...
    saslMechanisms: _MECHANISMS_
    saslUsername: _USERNAME_
    saslPassword: _PASSWORD_
}
----

`saslMechanisms`:: One or more SASL mechanisms to use to authenticate the router to the external container. You can choose any of the Cyrus SASL authentication mechanisms. To specify multiple authentication mechanisms, separate each mechanism with a space.
+
For a full list of supported Cyrus SASL authentication mechanisms, see link:https://www.cyrusimap.org/sasl/sasl/authentication_mechanisms.html[Authentication Mechanisms^].
`saslUsername`:: If any of the SASL mechanisms uses username/password authentication, then provide the username to connect to the external container.
`saslPassword`:: If any of the SASL mechanisms uses username/password authentication, then provide the password to connect to the external container.
--
