////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

[[cyrus_sasl]]
= Using Cyrus SASL to Provide Authentication

// Just doing some basic editing for now; for future releases, this content will need some more work. Also need to determine if it should be moved from an appendix to the section that deals with setting up SASL.

{RouterName} uses the Cyrus SASL library for SASL authentication. Therefore, if you want to use SASL, you must set up the Cyrus SASL database and configure it.

[[generating_sasl_database]]
== Generating a SASL Database

To generate a SASL database to store credentials, enter the following command:

[options="nowrap",subs="+quotes"]
----
# saslpasswd2 -c -f _SASL_DATABASE_NAME_.sasldb -u _DOMAIN_NAME_ _USER_NAME_
----

This command creates or updates the specified SASL database, and adds the specified user name to it. The command also prompts you for the user name's password.

// What is the goal here - to add user credentials to the database? If so, do you need to run this command for every user that you want to add? When it says that the command prompts for the password, does that mean you use the prompt to set the user's password?

The full user name is the user name you entered plus the domain name (`__USER_NAME__`@`__DOMAIN_NAME__`). Providing a domain name is not required when you add a user to the database, but if you do not provide one, a default domain will be added automatically (the hostname of the machine on which the tool is running). For example, in the command above, the full user name would be `user1@domain.com`.

== Viewing Users in a SASL Database

To view the user names stored in the SASL database:

[options="nowrap",subs="+quotes"]
----
# sasldblistusers2 -f qdrouterd.sasldb
user2@domain.com: __PASSWORD__
user1@domain.com: __PASSWORD__
----

[[configuring_sasl_database]]
== Configuring a SASL Database

To use the SASL database to provide authentication in {RouterName}:

. Open the `/etc/sasl2/qdrouterd.conf` configuration file.

. Set the following attributes:
+
--
[options="nowrap",subs="+quotes"]
----
pwcheck_method: auxprop
auxprop_plugin: sasldb
sasldb_path: __SASL_DATABASE_NAME__
mech_list: __MECHANISM1 ...__
----

`sasldb_path`:: The name of the SASL database to use.
+
For example:
+
[options="nowrap"]
----
sasldb_path: qdrouterd.sasldb
----

`mech_list`:: The SASL mechanisms to enable for authentication. To add multiple mechanisms, separate each entry with a space.
+
For example:
+
[options="nowrap"]
----
mech_list: ANONYMOUS DIGEST-MD5 EXTERNAL PLAIN
----
// Where can users find a list of supported mechanisms?
--
