////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

qdrouterd(8)
===========
:doctype: manpage

NAME
----
qdrouterd - routes AMQP messages.

SYNOPSIS
--------
*qdrouterd* ['OPTIONS']


DESCRIPTION
-----------
The Qpid Dispatch router ('qdrouterd') is a network daemon that directs
AMQP 1.0 messages between endpoints, such as messaging clients and
servers.

OPTIONS
-------

include::{generated_man}/qdrouterd_help.adoc[]

FILES
-----

{SYSCONF_INSTALL_DIR}/qdrouterd.conf::
  Configuration file.

SEE ALSO
--------
'qdrouterd.conf(5)', 'qdstat(8)', 'qdmanage(8)'

http://qpid.apache.org/components/dispatch-router
