////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-web-console.adoc

[id='accessing-web-console'-{context}']
= Accessing {ConsoleName}

You can access the web console from a web browser.

.Procedure

. In a web browser, navigate to the web console URL.
+
--
The web console URL is the _<host>_:__<port>__ from the `listener` that you created to serve the web console. For example: `localhost:8672`.

The {ConsoleName} opens. If you set up user name and password authentication, the *Connect* tab is displayed.
--

. If necessary, log in to the web console.
+
--
If you set up user name and password authentication, enter your user name and password to access the web console.

The syntax for the user name is <__user__>@<__domain__>. For example: `admin@my-domain`.
--
