////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// managing-router.adoc

[id='changing-router-configuration-{context}']
= Changing a router's configuration

You can make a permanent change to a router's configuration by editing the router's configuration file directly. You must restart the router for the changes to take effect, but the changes will be saved even if the router is stopped.

.Procedure

. Do one of the following:
+
--
** Edit the default configuration file (`{RouterConfigFile}`).
** Create a new configuration file.
--

. Start (or restart) the router.
+
--
For more information, see xref:starting-router-{context}[].

If you created a new configuration file, you must specify the path using the `--conf` parameter. For example, the following command starts the router with a non-default configuration file:

[options="nowrap",subs="+quotes"]
----
$ qdrouterd -d --conf /etc/qpid-dispatch/new-configuration-file.conf
----
--
