////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// configuring-network-connections.adoc

[id='connecting-to-external-amqp-containers-{context}']
= Connecting to external AMQP containers

To enable a router to establish a connection to an external AMQP container (such as a message broker), you configure a `connector`.

[NOTE]
====
Instead of configuring a `connector` to initiate connections to the AMQP container, you can configure a `listener` to listen for connections from the AMQP container. However, in this case, the addresses on the AMQP container are available for routing only after the AMQP container has created a connection.
====

.Procedure

include::{FragmentDir}/fragment-router-open-config-file-step.adoc[]

. Configure a `connector` with the `route-container` role.
+
--
This example creates a `connector` that initiates connections to a broker. The addresses on the broker will be available for routing once the router creates the connection and it is accepted by the broker.

[options="nowrap",subs="+quotes"]
----
connector {
    name: my-broker
    host: 192.0.2.10
    port: 5672
    role: route-container
    ...
}
----
`name`:: The name of the `connector`. Specify a name that describes the entity to which the router will connect.
`host`:: The IP address (IPv4 or IPv6) or hostname to which the router will connect.
`port`:: The port number or symbolic service name, defined in `/etc/services`, to which the router will connect.
`role`:: The role of the connection. Specify `route-container` to indicate that this connection is for an AMQP container that holds known addresses.
--

.Additional resources

* After enabling a router to connect to an external AMQP container, configure any necessary security credentials.
+
For more information, see xref:securing-outgoing-connections-{context}[].
