////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-web-console.adoc

[id='monitoring-router-network-web-console'-{context}']
= Monitoring the router network using {ConsoleName}

In the web console, you use the tabs to monitor the router network.

[cols="30,70"]
|===
| This tab... | Provides...

| `Overview` | Aggregated information about routers, addresses, links, connections, and logs.

| `Entities` | Detailed information about each AMQP management entity for each router in the router network. Some of the attributes have charts that you can add to the `Charts` tab.

| `Topology` | A graphical view of the router network, including routers, clients, and brokers. The topology shows how the routers are connected, and how messages are flowing through the network.

| `Charts` | Graphs of the information selected on the `Entities` tab.

| `Message Flow` | A chord diagram showing the real-time message flow by address.

| `Schema` | The management schema that controls each of the routers in the router network.

|===
