////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-web-console.adoc

[id='monitoring-router-network-web-console'-{context}']
= Monitoring the router network using {ConsoleName}

The web console provides several sections that you can use to monitor the router network.

[cols="25,75"]
|===
| This section... | Provides...

| Overview
a|
Aggregated information about the router network. This information includes the following:

* Dashboard (shows router network statistics)
* Routers
* Addresses
* Links
* Connections
* Logs

| Visualizations
a|
Graphical view of the router network. You can see the following types of visualizations:

`Topology`:: Topology of the router network, including routers, clients, and brokers. This visualization also shows how messages are flowing through the network.
`Message flow`:: A chord diagram showing the real-time message flow by address.

| Details
| Detailed configuration information about each AMQP management entity, for each router in the router network. You can view and change the configuration of any of the routers in the network.

|===
