////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// getting-started.adoc

[id='next-steps-{context}']
= Next steps

After you successfully install a standalone router and use it to distribute messages between two clients, you can configure a router network topology and route messages.

Configure a router network topology::
After configuring a single router, you can deploy additional routers and connect them together to form a router network. Router networks can be any arbitrary topology.

Route messages through the router network::
Regardless of the underlying router network topology, you can configure how you want messages to be routed through the router network.
+
--
* Configure addresses to specify routing patterns for direct-routed (brokerless) messaging
* Connect the router to a message broker to enable clients to exchange messages with a broker queue.
* Create link routes to define private messaging paths between endpoints.
--
+
For more information, see xref:routing[].
