////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// getting-started.adoc

[id='next-steps-{context}']
= Next steps

After using {RouterName} to distribute messages between two clients, you can use the following sections to learn more about {RouterName} configuration, deployment, and management.

xref:configuration[Change the router's configuration]::
{RouterName} ships with default settings that are suitable for many basic use cases. You can further experiment with the standalone router that you used in the _Getting started_ example by changing the router's essential properties, network connections, security settings, logging, and routing mechanisms.

xref:installing-router-{context}[Install and configure {RouterName}]::
{RouterName} is typically deployed in router networks. You can design a router network of any arbitrary topology to interconnect the endpoints in your messaging network.

xref:management[Monitor and manage {RouterName}]::
You can use the web console and command-line management tools to monitor the status and performance of the routers in your router network.
