////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module included in the following assemblies:
//
// important-terms-concepts.adoc

[id='router-security-{context}']
= Router security

{RouterName} provides authentication and authorization mechanisms so that you can control who can access the router network, and what they can do with the messaging resources.

Authentication::
{RouterName} supports both SSL/TLS and SASL for encrypting and authenticating remote peers. Using these mechanisms, you can secure the router network in the following ways:

* Authenticate incoming connections from remote peers (such as clients and message brokers)
* Provide authentication credentials for outgoing connections to remote peers (such as clients and message brokers)
* Secure the inter-router connections between the routers in the router network

Authorization::
{RouterName} provides a `policy` mechanism that you can use to enforce user connection restrictions and AMQP resource access control.

.Additional resources

* xref:securing-network-connections-{context}[]

* xref:configuring-authorization-{context}[]
