////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// securing-network-connections.adoc

[id='securing-connections-between-routers-{context}']
= Securing connections between routers

Connections between interior routers should be secured with SSL/TLS encryption and authentication (also called mutual authentication) to prevent unauthorized routers (or endpoints pretending to be routers) from joining the network.

SSL/TLS mutual authentication requires an X.509 Certificate Authority (CA) with individual certificates generated for each interior router. Connections between the interior routers are encrypted, and the CA authenticates each incoming inter-router connection.

This procedure describes how to secure a connection between two interior routers using SSL/TLS mutual authentication.

.Prerequisites

* An X.509 Certificate Authority must exist for the interior routers.

* A security certificate must be generated for each router and be signed by the CA.

* An inter-router connection must exist between the routers.
+
For more information, see xref:connecting-routers-{context}[].

.Procedure

. On the router that establishes the connection, do the following:

.. Open the `{RouterConfigFile}`.

.. If the router does not contain an `sslProfile` that defines the private keys and certificates for the inter-router network, then add one.
+
--
This `sslProfile` contains the locations of the private key and certificates that the router uses to authenticate with its peer.

[options="nowrap",subs="+quotes"]
----
sslProfile {
    name: inter-router-tls
    certFile: /etc/pki/tls/certs/tls.crt
    caCertFile: /etc/pki/tls/certs/ca.crt
    privateKeyFile: /etc/pki/tls/private/tls.key
    password: file:/etc/pki/tls/private/password.txt
    ...
}
----
`name`:: A unique name that you can use to refer to this `sslProfile`.

`certFile`:: The absolute path to the file containing the public certificate for this router.

`caCertFile`:: The absolute path to the CA certificate that the router uses to authenticate incoming clients.

`privateKeyFile`:: The absolute path to the file containing the private key for this router's public certificate.
+
[NOTE]
====
Ensure that the `qdrouterd` or root user can access the private key. For example:

[options="nowrap",subs="+quotes"]
----
chmod 0600 /etc/pki/tls/private/tls.key
chown qdrouterd /etc/pki/tls/private/tls.key
----
====

//`password`
include::{FragmentDir}/fragment-password-description.adoc[]
--

.. Configure the inter-router `connector` for this connection to use the `sslProfile` that you created.
+
--
[options="nowrap",subs="+quotes"]
----
connector {
    host: 192.0.2.1
    port: 5001
    role: inter-router
    sslProfile: inter-router-tls
    ...
}
----
`sslProfile`:: The name of the `sslProfile` that defines the SSL/TLS private keys and certificates for the inter-router network.
--

. On the router that listens for the connection, do the following:

.. Open the `{RouterConfigFile}`.

.. If the router does not contain an `sslProfile` that defines the private keys and certificates for the inter-router network, then add one.

.. Configure the inter-router `listener` for this connection to use SSL/TLS to secure the connection.
+
--
[options="nowrap",subs="+quotes"]
----
listener {
    host: 0.0.0.0
    port: 5001
    role: inter-router
    sslProfile: inter_router_tls
    authenticatePeer: yes
    requireSsl: yes
    saslMechanisms: EXTERNAL
    ...
}
----
`sslProfile`:: The name of the `sslProfile` that defines the SSL/TLS private keys and certificates for the inter-router network.

`authenticatePeer`:: Specify `yes` to authenticate the peer interior router's identity.

`requireSsl`:: Specify `yes` to encrypt the connection with SSL/TLS.

`saslMechanisms`:: Specify `EXTERNAL` to enable X.509 client certificate authentication.
--
