////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module included in the following assemblies:
//
// overview.adoc

[id='supported-standards-protocols-{context}']
= Supported standards and protocols

{RouterName} supports the following industry-recognized standards and network protocols:

include::{FragmentDir}/fragment-supported-standards-protocols-list.adoc[]

[NOTE]
====
The details of distributed transactions (XA) within AMQP are not provided in the 1.0 version of the specification. AMQ Interconnect does not support XA transactions.
====

.Additional resources

include::{FragmentDir}/fragment-supported-standards-additional-resources.adoc[]
