////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-qdstat.adoc

[id='syntax-using-qdstat-{context}']
= Syntax for using `qdstat`

You can use `qdstat` with the following syntax:

[options="nowrap",subs="+quotes"]
----
$ qdstat __<option>__ [__<connection-options>__] [__<secure-connection-options>__]
----

This specifies:

* An _option_ for the type of information to view.
* One or more optional _connection options_ to specify a router for which to view the information.
+
If you do not specify a connection option, `qdstat` connects to the router listening on localhost and the default AMQP port (5672).
* The _secure connection options_ if the router for which you want to view information only accepts secure connections.

.Additional resources

* For more information about `qdstat`, see the {qdstatManPageLink}.
