////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// book.adoc

[id='configuring-router-{context}']
= Configuring {RouterName}

Each {RouterName} router contains a `qdrouterd.conf` configuration file. You edit this file to define how the router should operate.

You can do the following:

* xref:configuring-router-properties-{context}[Configure essential router properties]
* xref:configuring-network-connections-{context}[Configure network connections]
* xref:securing-network-connections-{context}[Secure network connections]
* xref:authorizing-access-messaging-resources-{context}[Authorize access to messaging resources]
* xref:configuring-logging-{context}[Configure logging]

// Configuring router properties
include::../../modules/user-guide/configuring-router-properties.adoc[leveloffset=+1]

// Configuring network connections
include::configuring-network-connections.adoc[leveloffset=+1]

// Securing network connections
include::securing-network-connections.adoc[leveloffset=+1]

// Authorizing access to messaging resources
include::authorizing-access-messaging-resources.adoc[leveloffset=+1]

// Configuring logging
include::configuring-logging.adoc[leveloffset=+1]
