////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// configuring-message-routing.adoc

[id='configuring-brokered-messaging-{context}']
= Configuring brokered messaging

If you require "store and forward" capabilities, you can configure {RouterName} to use brokered messaging. In this scenario, clients connect to a router to send and receive messages, and the router routes the messages to or from queues on a message broker.

You can configure the following:

* xref:routing-messages-through-broker-queues-{context}[Route messages through broker queues]
+
You can route messages to a queue hosted on a single broker, or route messages to a _sharded queue_ distributed across multiple brokers.

* xref:handling-undeliverable-messages-{context}[Store and retrieve undeliverable messages on a broker queue]

include::../../modules/user-guide/how-router-enables-brokered-messaging.adoc[leveloffset=+1]

include::../../modules/user-guide/routing-messages-through-broker-queues.adoc[leveloffset=+1]

include::../../modules/user-guide/handling-undeliverable-messages-for-address.adoc[leveloffset=+1]
