////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// book.adoc

ifdef::context[:parent-context: {context}]

[id='getting-started-{context}']
= Getting started

This section provides a quick introduction to {RouterName} by showing you how to install {RouterName}, start the router with the default configuration settings, and distribute messages between two clients.

:context: getting-started
include::../../modules/user-guide/installing-router-linux.adoc[leveloffset=+1]
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

include::../../modules/user-guide/exploring-default-router-configuration-file.adoc[leveloffset=+1]

include::../../modules/user-guide/starting-router-getting-started.adoc[leveloffset=+1]

include::../../modules/user-guide/sending-test-messages.adoc[leveloffset=+1]

include::../../modules/user-guide/next-steps.adoc[leveloffset=+1]
