////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// book.adoc

[id='getting-started-{context}']
= Getting started

This section shows you how to start the {RouterName} with the default configuration settings, and distribute messages between two clients.

.Prerequisites

* {RouterName} must be installed.
+
For more information, see xref:installing-router-{context}[].

// Viewing the default router configuration file
include::../../modules/user-guide/viewing-default-router-configuration-file.adoc[leveloffset=+1]

// Starting the router
include::../../modules/user-guide/starting-router-getting-started.adoc[leveloffset=+1]

// Sending some test messages
include::../../modules/user-guide/sending-test-messages.adoc[leveloffset=+1]

// Next steps
include::../../modules/user-guide/next-steps.adoc[leveloffset=+1]
