////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// creating-router-network-topology.adoc

[id='router-deployment-guidelines-{context}']
= {RouterName} deployment guidelines

To plan your router network and design the network topology, you must first understand the different router modes and how you can use them to create different types of networks.

// Router operating modes
include::../../modules/user-guide/router-operating-modes.adoc[leveloffset=+1]

// Security guidelines
include::../../modules/user-guide/security-guidelines.adoc[leveloffset=+1]

// Router connection guidelines
include::../../modules/user-guide/router-connection-guidelines.adoc[leveloffset=+1]
