////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// securing-network-connections.adoc

[id='securing-outgoing-connections-{context}']
= Securing outgoing connections

If a router is configured to create connections to external AMQP containers (such as message brokers), you can use the following methods to secure the connection:

* xref:connecting-using-one-way-ssl-tls-authentication-{context}[Connect using SSL/TLS encryption (one-way authentication)]
* xref:connecting-using-mutual-ssl-tls-authentication-{context}[Connect using SSL/TLS mutual authentication]
* xref:connecting-using-username-password-authentication-{context}[Connect using user name and password authentication (with or without SSL/TLS encryption)]

// Connecting using SSL/TLS encryption
include::../../modules/user-guide/connecting-using-one-way-ssl-tls-authentication.adoc[leveloffset=+1]

// Connecting using SSL/TLS mutual authentication
include::../../modules/user-guide/connecting-using-mutual-ssl-tls-authentication.adoc[leveloffset=+1]

// Connecting using user name and password authentication
include::../../modules/user-guide/connecting-using-username-password-authentication.adoc[leveloffset=+1]
