////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// securing-network-connections.adoc

[id='securing-incoming-client-connections-{context}']
= Securing incoming client connections

You can use SSL/TLS and SASL to provide the appropriate level of security for client traffic into the router network. You can use the following methods to secure incoming connections to a router from AMQP clients, external containers, or edge routers:

* xref:enabling-ssl-tls-encryption-{context}[Enable SSL/TLS encryption]
* xref:enabling-ssl-tls-client-authentication-{context}[Enable SSL/TLS client authentication]
* xref:enabling-username-password-authentication-{context}[Enable user name and password authentication]
* xref:integrating-with-kerberos-{context}[Integrate with Kerberos]

// Enabling SSL/TLS encryption
include::../../modules/user-guide/enabling-ssl-tls-encryption.adoc[leveloffset=+1]

// Enabling SSL/TLS client authentication
include::../../modules/user-guide/enabling-ssl-tls-client-authentication.adoc[leveloffset=+1]

// Enabling username/password authentication
include::../../modules/user-guide/enabling-username-password-authentication.adoc[leveloffset=+1]

// Integrating with Kerberos
include::../../modules/user-guide/integrating-with-kerberos.adoc[leveloffset=+1]
