////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

[[configuration]]
Configuration
-------------

The default configuration file is installed in
'{CMAKE_INSTALL_PREFIX}/etc/qpid-dispatch/qdrouterd.conf'. This configuration file will
cause the router to run in standalone mode, listening on the standard
AMQP port (5672). Dispatch Router looks for the configuration file in
the installed location by default. If you wish to use a different path,
the "-c" command line option will instruct Dispatch Router as to which
configuration to load.

To run the router, invoke the executable: `qdrouterd [-c my-config-file]`

For more details of the configuration file see the 'qdrouterd.conf(5)' man
page.
