////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

= Packaging

== rpm

The https://packit.dev/docs/cli[`packit` tool] expects to have a `.packit.yaml` file at the source root.

.Example: install build dependencies
[source,shell script]
----
dnf install 'dnf-command(builddep)'
dnf builddep -y packaging/skupper-router.spec
----

.Example: local packit build
[source,shell script]
----
packit build locally
----

https://copr.fedorainfracloud.org/[COPR] builds can be triggered with Packit (`packit build`) as well.
