////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// book.adoc

[id='configuring-router-network-topology-{context}']
= Configuring a router network topology

You can deploy {RouterName} as a single standalone router, or as multiple routers connected together in a router network. Router networks can be any arbitrary topology, enabling you to design the network to best fit your requirements.

With {RouterName}, the router network topology is independent from the message routing. This means that messaging clients always experience the same message routing behavior regardless of the underlying network topology. Even in a multi-site or hybrid cloud router network, the connected endpoints behave as if they were connected to a single, logical router.

To configure the router network topology, complete the following:

. xref:planning-router-network-router[Plan the router network].
+
You should understand the different router operating modes you can deploy in your topology, and be aware of security requirements for the interior portion of the router network.

. xref:adding-routers-router-network-router[Build the router network by adding routers one at a time].
+
For each router, you must configure the following:
+
** Router properties
** Network connections (incoming and outgoing)
** Security (authentication and authorization)

// Planning a router network
include::planning-router-network.adoc[leveloffset=+1]

// Adding routers to the router network
include::modules/adding-routers-router-network.adoc[leveloffset=+1]

// Configuring router properties
include::modules/configuring-router-properties.adoc[leveloffset=+1]

// Configuring network connections
include::configuring-network-connections.adoc[leveloffset=+1]

// Securing network connections
include::securing-network-connections.adoc[leveloffset=+1]

// Authorizing access to messaging resources
include::../authorization.adoc[leveloffset=+1]
