////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// adding-routers-router-network.adoc

[id='configuring-network-connections-{context}']
= Configuring network connections

{RouterName} connects clients, servers, AMQP services, and other routers through network connections. To connect the router to other messaging endpoints, you configure _listeners_ to accept connections, and _connectors_ to make outbound connections. However, connections are bidirectional - once the connection is established, message traffic flows in both directions.

You can configure the following types of connections:

`inter-router`:: The connection is for another interior router in the network. Inter-router discovery and routing protocols can only be used over inter-router connections.
`normal`:: The connection is for AMQP clients using normal message delivery.
`edge`:: The connection is between an edge router and an interior router.
`route-container`:: The connection is for a broker or other resource that holds known addresses.

// Connecting routers
include::modules/connecting-routers.adoc[leveloffset=+1]

// Listening for client connections
include::modules/listening-client-connections.adoc[leveloffset=+1]

// Creating a connection to an external AMQP container
include::modules/connecting-routers-external-amqp-containers.adoc[leveloffset=+1]

// Connection failover
include::modules/connection-failover.adoc[leveloffset=+1]
