////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// important-terms-concepts.adoc

ifdef::context[:parent-context: {context}]

[id='router-routing-{context}']
= Routing
:context: terms-concepts-routing

In a router network, _routing_ is the process by which messages are delivered to their destinations. To accomplish this, {RouterName} offers two different routing mechanisms: _message routing_, which enables you to route messages based on anycast and multicast routing patterns, and _link routing_, which enables you to establish a dedicated, virtual path between a sender and receiver.

include::modules/message-routing.adoc[leveloffset=+1]

include::modules/link-routing.adoc[leveloffset=+1]

// Restore the context to what it was before this assembly.
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
